# Generated by Django 3.2 on 2021-04-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsrMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromval', models.FloatField(blank=True, null=True)),
                ('toval', models.FloatField(blank=True, null=True)),
                ('chaptername', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('psr_rule', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'psr_master',
                'managed': False,
            },
        ),
    ]
